version: '3.9'

services:
  # app:
  #   build: .
  #   container_name: app
  #   restart: on-failure
  #   volumes:
  #     - ".:/app"
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
